### ISSUE TITLE
Add default icons for each entity if none is specified

### ISSUE THREAD

**Issue by BrailleBennett** [TechnicJelle/BlueMapFilteredEntities#10]
Add the head of the enemy as the point marker icon, or in the case of non mob entities add the block or thing that it is. This would greatly increase the presentation of the map and make it easy to see what each mob is at a glance.

**Comment by TechnicJelle** [comment]
This would require me to ship hundreds of PNGs with the plugin, for each type of entity and for each block. This is not something that I want to do. It is also completely outside the responsibility of this plugin.
This plugin allows users to set up their own filters with their own icons.
Users will have to provide their own icons for their own filters.
If they do not provide a custom icon, it will use the default BlueMap icon.

Feel free to build your own collection of marker images and filter configs, and then you could even release them.
Maybe I'll have a section that links to some example setups in the readme.
