### ISSUE TITLE
Split each entity into its own marker set

### ISSUE THREAD

**Issue by BrailleBennett** [TechnicJelle/BlueMapFilteredEntities#3]
I think that, optionally, or if more than a few entities are being filtered in, that each different type of entity should be split into its own marker set if > 0 are currently loaded/detected by the plugin. This way, you avoid the performence issues of trying  to load 800 different entity markers at the same time. This also puts more control into the hands of the user, and not just the server staff, as players can choose to show what type of enemies/animals they have loaded on their map at once.

**Comment by BrailleBennett** [comment]
Perhaps this could be used to achieve that in a not spammy way if it ever gets considered/implemented:
https://github.com/BlueMap-Minecraft/BlueMap/issues/544

**Comment by TechnicJelle** [comment]
My idea for this was something like this:
```hocon
filter-sets: {
  flyers: {
    label: "Flying entities"
    toggleable: true
    default-hidden: true
    filters: [
      { type: bat }
      { type: parrot }
      { type: phantom }
    ]
  }
  grazers: {
    label: "Entities that graze grass"
    toggleable: true
    default-hidden: false
    filters: [
      { type: cow }
      { type: pig }
      { type: sheep }
    ]
  }
}
```
This kind of replicates the built-in [BlueMap marker](https://bluemap.bluecolored.de/wiki/customization/Markers.html) format, which should hopefully make it simpler for users to learn, if they already know that.

**Comment by BrailleBennett** [comment]
Will the set names and contents be controlled by the user or automatically predefined and static?

**Comment by TechnicJelle** [comment]
The set ID and label will both be controlled by the user, in exactly the same way as the normal BlueMap marker config does it: https://bluemap.bluecolored.de/wiki/customization/Markers.html#marker-sets
The contents (aka the actual markers in the set) will be filled by the plugin, automatically. But! It'll be controlled by the user, of course, by the filters.
