### ISSUE TITLE
Have a way to switch the filter to a blacklist mode

### ISSUE THREAD

**Issue by BrailleBennett** [TechnicJelle/BlueMapFilteredEntities#5]
Add a config option, Boolean, that when true changes the list of filtered entities to a blacklist instead of a white list. This way server owners could blacklist certain entities like fish, enderman, or boss mobs that may be a performence issue or a spoiler for players. This would also double as a clean way to allow someone to display all entities at once if they set the filter list to a blacklist mode and don't add any entities to be blacklisted.

**Comment by TechnicJelle** [comment]
The way to blacklist/exclude entities will be done like this: https://github.com/TechnicJelle/BlueMapFilteredEntities/blob/9e2d65c1a34e2e1b231761af75d4bc474a66070d/example.conf#L45-L53
And while it's currently not implemented yet, it will be soon™

**Comment by BrailleBennett** [comment]
If you have only blacklisted entities in conf will everything else be whitelisted automatically?

**Comment by TechnicJelle** [comment]
I think I'll make it so you can't have a filter that's *only* a blacklist.
