### ISSUE TITLE
Make conf files more clear

### ISSUE THREAD

**Issue by BrailleBennett** [TechnicJelle/BlueMapFilteredEntities#6]
Keep the two example entities in the file, and also add a link to all valid entities that can be used and maybe all valid data parameters like type, name, etc. that can also be used.

**Comment by TechnicJelle** [comment]
Finished in 64584579d1aed21d383b80286cfc21456a8cd458.
But let me know if there's anything else that's unclear or should be explained (more).
I'm sure I've forgotten *some*thing
